Repository wtsi-npg/npg_conda, pull requests merged in 2020-07, with the labels that each got.

#153 Add --provides CLI option
  scripts/package_sort.py
Labels: enhancement

#152 Bugfix: handle required package with no version
  scripts/package_sort.py
Labels: bug, documentation

#160 Add recipe for valet 1.3.0
  recipes/valet/1.3.0/build.sh
  recipes/valet/1.3.0/meta.yaml
Labels: enhancement

#161 bugfix: fasta_formatter required missing lib
  recipes/fastx_toolkit/0.0.14/meta.yaml
Labels: bug
