Repository wtsi-npg/npg_conda, pull requests merged in 2021-04, with the labels that each got.

#231 Add iRODS 4.2.8
  recipes/avrocpp/1.9.0/build.sh
  recipes/avrocpp/1.9.0/meta.yaml
  recipes/boost/1.73.0/conda_build_config.yaml
  recipes/json/3.9.1/build.sh
  recipes/json/3.9.1/meta.yaml
  recipes/krb5/1.19.1/build.sh
  recipes/krb5/1.19.1/meta.yaml
  recipes/libarchive/3.5.1/build.sh
  recipes/libarchive/3.5.1/meta.yaml
  recipes/nanodbc/2.13.0/build.sh
  recipes/nanodbc/2.13.0/meta.yaml
  red-recipes/irods/4.2.8/build.sh
  red-recipes/irods/4.2.8/conda_build_config.yaml
  red-recipes/irods/4.2.8/irods.patch
  red-recipes/irods/4.2.8/irods_icommands.patch
  red-recipes/irods/4.2.8/meta.yaml
Labels: Work in progress, enhancement

#238 Improve differentiation of branch names by appending sha of source url
  scripts/mirror_repo.sh
Labels: bug

#239 Move from Travis CI to GitHub Actions
  .github/workflows/unit-tests.yml
  .travis.yml
Labels: enhancement

#242 Add libraries and pkgconfig missing from the package
  recipes/krb5/1.19.1/build.sh
  recipes/krb5/1.19.1/meta.yaml
Labels: bug
